---
title: "Home"
site: workflowr::wflow_site
---

Welcome! This is a website for organizing the summaries of my meetings and readings.
[Rmarkdown cheatsheet](cheatsheat.html)

<style>
.column-left{
  float: left;
  width: 100%;
  text-align: left;
}
.column-center{
  display: inline-block;
  width: 100%;
  text-align: center;
}
.column-right{
  float: right;
  width: 20%;
  text-align: right;
}
</style>



<div class="column-left">

# 2021 meeting document

* ## [TO-DO LIST before manuscript submission](paper_writing_plan.html)
* ## Workflow overview updated on 18 Jan 2021
    *   [Workflow diagram (Sequins analysis based on the truth)](Workflow_Diagram.pdf)
    *   [Workflow diagram (Sequins analysis assuming truth unknown)](Workflow_Diagram2.pdf)
* ## [5 Feb meeting notes](Feb5_meeting_note.pdf)
* ## [10 Feb meeting notes](Feb10_meeting_note.pdf)
* ## [17 Feb meeting notes](Feb_17_meeting_notes.pdf)
* ## [All figure for paper (draft)](Paper_figure.pdf)
* ## [H_i distribution generate update](S_i empirical_distribution.pdf)
* ## [18 Feb meeting(paper outline)](Meeting_summary20210218.pdf)
* ## [24 Feb meeting(paper outline)](Meeting_summary20210224.pdf)
* ## [03 Mar meeting(main figure update)](Main_figure_update_(Mar_03_2021).pdf)



# Problem and discussion
* ### [Project description](5_Mar_with_HJ_and_MK_.html) (Meeting with Heejung and Mike,5 Mar 2019)
* ### [Initial idea about the solution](18_Mar_with_HJ_and_MK.html) (Meeting with Heejung and Mike,18 Mar 2019)
* ### [Progress Update](10_Apr_Meeting_Summary.html) (Meeting with Heejung and Mike, 10 Apr 2019)
* ### [Problem and Discussion](Problem_and_Discussion.html)

# Reading
* ### [Real-time selective sequencing using nanopore technology](Matthew_2016.html)
* ### [Using sequins with RNA sequencing](Using_sequins_with_RNA_sequencing.html)

# Software
* ### [SquiggleKit](SquiggleKit.html)
* ### [Tombo resquiggle Algorithm](Tombo_resquiggle.html)
* ### [FLAIR (exon junction correction)](FLAIR.html)

# Workflow
* ### [cDNA dataset preprocessing](cDNA_data_preprocessing.html)
* ### [Fetch signal from tombo output](fetch_single_from_tombo.html)
* ### Single Splicing site test
  * #### [Single splicing site and tested reads](cDNA_R1_102_1.html)
  * #### [Generate candidates](candidate_generator.html)
  * #### [Generate representative squiggle for candidates](get_representative_squiggle.html)
  * #### [Run self-developed DTW](self_developed_DTW.html)
  
* ### [Probabilistic model](probabilistic_model.html)
  - [log-sum-exp trick](log-sum-exp.html)

* ### [snakemake pipeline](snakemake_pipline.html)
  * #### [Test 1:](f15_t4_mad_norm.html)
    settings:
      *   dtw cost function: -log(f(z)), f is standard normal
      *   exon junction flank: 15 bases in each side
      *   scrappie model trim: 4 bases in each side
      *   normalisation: global mad normalisation for real signal
  * #### [Pipeline test summary](pipeline_test_summary.html)

      

* ### [Short read Analysis](Short_Read_preprocessing.html)



# Document

* [Comfirmation report](Confirmation_Report_Yupei.pdf)

</div>

```{r eval=FALSE, include=FALSE}
* #### [Inaccurate transcript checking](inaccurate_transcript_checking.html)
  
```

